repos:
  - repo: https://github.com/python/black
    rev: 19.10b0
    hooks:
      - id: black
  - repo: https://github.com/prettier/prettier
    rev: 2.0.4
    hooks:
      - id: prettier
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: env -i PATH=./bin:./.venv/bin:./venv/bin:./.virtualenv/bin:./virtualenv python -m flake8
        language: system
        types: [python]
        exclude: /migrations/
