version: '3.1'

services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-oeGEHyS4}
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8008:8080
