# Generated by Django 3.0.5 on 2020-04-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gym",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("opens_at", models.TimeField(verbose_name="Opens at")),
                ("closes_at", models.TimeField(verbose_name="Closes at")),
            ],
        ),
    ]
