# Generated by Django 3.0.5 on 2020-04-26 16:44

import core.models.booking
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "pin",
                    models.PositiveSmallIntegerField(default=core.models.booking.pin),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "NEW"),
                            ("EXPIRED", "EXPIRED"),
                            ("CONFIRMED", "CONFIRMED"),
                            ("CANCELED", "CANCELED"),
                            ("NOSHOW", "NOSHOW"),
                        ],
                        default="NEW",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("phone_no_hash", models.CharField(max_length=255)),
                ("date", models.DateField(default=datetime.date.today)),
                ("start", models.TimeField()),
                ("end", models.TimeField()),
                ("checkin_at", models.TimeField(null=True)),
                ("checkout_at", models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Gym",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        help_text="A short name that is used in URLs.",
                        verbose_name="Shortname",
                    ),
                ),
                ("opens_at", models.TimeField(verbose_name="Opens at")),
                ("closes_at", models.TimeField(verbose_name="Closes at")),
            ],
        ),
        migrations.CreateModel(
            name="PhoneNumber",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hash", models.CharField(max_length=255, unique=True)),
                ("verified_at", models.DateTimeField(null=True)),
                (
                    "blocked_due_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.Booking",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="booking",
            name="gym",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.Gym"
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(status__in=["NEW", "CONFIRMED"]),
                fields=("name",),
                name="unique_name",
            ),
        ),
    ]
