# Generated by Django 3.0.5 on 2020-04-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gym",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                default="bouldergarten",
                help_text="A short name that is used in URLs.",
                verbose_name="Shortname",
            ),
            preserve_default=False,
        ),
    ]
