# Generated by Django 3.0.5 on 2020-05-18 12:08

import core.models.user
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user", managers=[("objects", core.models.user.CustomUserManager()),],
        ),
        migrations.AddField(
            model_name="user",
            name="gym",
            field=models.ForeignKey(
                help_text="The gym this user can manage.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.Gym",
            ),
        ),
    ]
