# Generated by Django 3.0.5 on 2020-04-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gym",
            name="max_guests",
            field=models.PositiveSmallIntegerField(
                default=100,
                help_text="Maximum number of people that are allowed to occupy the space simultaneously. Also the maximum number of bookings for a time slot.",
            ),
        ),
    ]
